# Generated by Django 2.0.4 on 2018-07-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180627_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
